## Supports Ubuntu 24.x (minimal)
---
-
  name: Depoying CloudPBX Freepbx
  hosts: all
  become: true
  vars:
    db_root_pass: "{{ lookup('env','DB_ROOT_PASS') }}"
    fpbx_ver: 17.0
    ast_ver: 21
    nodejs_ver: 18
  roles:
    - sysprep
    - db_prep
    - asterisk
    - freepbx
    - phpmyadmin
    - webmin
