---
- name: Ensure MariaDB service is running and enabled
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Wait for MariaDB socket to become available
  ansible.builtin.wait_for:
    path: /var/run/mysqld/mysqld.sock
    state: present
    timeout: 30

- name: Change DB listener from localhost to all interfaces (0.0.0.0)
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address\s*=\s*127\.0\.0\.1'
    line: "bind-address = 0.0.0.0"
    backrefs: yes
  notify: Restart mariadb

- name: Ensure sql_mode is not overly strict (remove STRICT_TRANS_TABLES)
  ansible.builtin.blockinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    block: |
      [mysqld]

      sql_mode=''
    marker: "
    insertafter: '^\[mysqld\]'
  notify: Restart mariadb


- name: Set MariaDB root password for localhost access using SQL query (ALTER USER)
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_pass }}';"
  register: root_password_set_alter
  changed_when: root_password_set_alter.rowcount | default(0) > 0 or root_password_set_alter.query_affected_rows | default(0) > 0


- name: Flush MariaDB privileges after setting root password
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: "FLUSH PRIVILEGES;"
  when: root_password_set_alter.changed


- name: Remove anonymous MariaDB users
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: ""
    host_all: yes
    state: absent

- name: Remove MariaDB 'test' database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: test
    state: absent

- name: Create 'asteriskcdrdb' database
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: asteriskcdrdb
    state: present

- name: Create 'freepbxuser' for FreePBX database access
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ db_root_pass }}"
    name: "{{ db_fpbx_user }}"
    password: "{{ db_fpbx_pass }}"
    host: localhost

    priv: "asteriskcdrdb.*:ALL/asterisk.*:ALL"
    state: present
