---
packages:
  - build-essential
  - linux-headers-{{ ansible_kernel }}
  - pkg-config
  - automake
  - autoconf
  - libtool
  - libtool-bin
  - openssh-server
  - sudo
  - git
  - subversion
  - curl
  - wget
  - dirmngr
  - apt-transport-https
  - ca-certificates
  - gnupg
  - vim
  - expect
  - cron
  - logrotate
  - xz-utils
  - apache2
  - mariadb-server
  - mariadb-client
  - php8.2
  - php8.2-cli
  - php8.2-common
  - php8.2-curl
  - php8.2-gd
  - php8.2-intl
  - php8.2-mbstring
  - php8.2-mysql
  - php8.2-odbc
  - php8.2-pdo
  - php8.2-xml
  - php8.2-zip
  - php-pear
  - libncurses5-dev
  - libssl-dev
  - libxml2-dev
  - libsqlite3-dev
  - uuid-dev
  - libjansson-dev
  - libasound2-dev
  - libogg-dev
  - libvorbis-dev
  - libicu-dev
  - libcurl4-openssl-dev
  - libical-dev
  - libneon27-dev
  - libsrtp2-dev
  - libspandsp-dev
  - libedit-dev
  - libgmime-3.0-dev
  - unixodbc
  - unixodbc-dev
  - odbc-mariadb
  - sox
  - mpg123
  - lame
  - ffmpeg
  - nodejs
  - python3
  - python3-pip
  - python3-mysqldb
  - python3-dev
  - sendmail-bin
  - sendmail
  - sngrep
  - debconf-utils
