---
-
  name: Download Asterisk {{ast_ver}}
  get_url:
    url: http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-{{ast_ver}}-current.tar.gz
    dest: /usr/src
-
  name: Untar Asterisk tarball
  unarchive:
    src: /usr/src/asterisk-{{ast_ver}}-current.tar.gz
    dest: /usr/src
    remote_src: yes
-
  name: Remove Asterisk tarball
  file:
    path: /usr/src/asterisk-{{ast_ver}}-current.tar.gz
    state: absent
-
  name: "Find extracted Asterisk {{ast_ver}} folder name "
  find:
    paths: /usr/src
    file_type: directory
    recurse: no
    patterns: ^asterisk.*$
    use_regex: yes
  register: 'ast_install_dir'
- 
  name: "Make Libvpb1 install non-interactive"
  shell: echo 'libvpb1 libvpb1/countrycode string 381' | sudo debconf-set-selections -v
-
  name: Install Asterisk Prereqisites
  shell: 
    cmd: "{{item}}"
    chdir: "{{ast_install_dir.files[0].path}}/contrib/scripts"
  with_items:
    - ./get_mp3_source.sh
    - ./install_prereq install
-
  name: Run configure asterisk scripts
  shell: 
    cmd: ./configure --with-pjproject-bundled --with-jansson-bundled
    chdir: "{{ast_install_dir.files[0].path}}"
-
  name: Select make options
  shell: 
    cmd: "{{item}}"
    chdir: "{{ast_install_dir.files[0].path}}"
  with_items:
    - make menuselect.makeopts
    - menuselect/menuselect --enable res_config_mysql --enable format_mp3 menuselect.makeopts
-
  name: Compile and Install Asterisk
  shell: 
    cmd: "{{item}}"
    chdir: "{{ast_install_dir.files[0].path}}"
  with_items:
    - make
    - contrib/scripts/get_mp3_source.sh
    - make install
    - make config
    - ldconfig
    - update-rc.d -f asterisk remove
-
  name: Add asterisk users
  user:
    name: asterisk
    comment: Asterisk user
-
  name: Seting folder permitions for asterisk user
  file:
    path: "{{item}}"
    owner: asterisk
    group: asterisk
    state: directory
    recurse: yes
  with_items:
    - /var/run/asterisk
    - /etc/asterisk
    - /var/lib/asterisk
    - /var/log/asterisk
    - /var/spool/asterisk
    - /usr/lib/asterisk
-
  name: Remove default web folder
  file:
    path: /var/www/html
    state: absent
-
  name: "Find php version folder name "
  find:
    paths: /etc/php
    file_type: directory
    recurse: no
    patterns: ^8.*$
    use_regex: yes
  register: 'php_ver'
-
  name: Making some Apache config changes
  lineinfile:
    path: "{{item.path}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    -
      path: "{{php_ver.files[0].path}}/apache2/php.ini"
      regexp: "upload_max_filesize ="
      line: "upload_max_filesize = 20M"
    -
      path: "{{php_ver.files[0].path}}/apache2/php.ini"
      regexp: "memory_limit ="
      line: "memory_limit = 256M"
    -
      path: /etc/apache2/envvars
      regexp: export APACHE_RUN_USER=
      line: export APACHE_RUN_USER=asterisk
    -
      path: /etc/apache2/envvars
      regexp: export APACHE_RUN_GROUP=
      line: export APACHE_RUN_GROUP=asterisk
-
  name: Some more Apache changes
  replace:
    path: '/etc/apache2/apache2.conf'
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
-
  name: Enable Apache Rewrite Mod
  shell: a2enmod rewrite
-
  name: Restarting Apache Service
  service:
    name: apache2
    state: restarted
-
  name: Seting ODBC files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    -
      src: odbc.ini.j2
      dest: /etc/odbc.ini
    -
      src: odbcinst.ini.j2
      dest: /etc/odbcinst.ini
