---
- name: Define base Asterisk version variable
  ansible.builtin.set_fact:
    asterisk_version: "{{ ast_ver }}"

- name: Define Asterisk download URL and archive path
  ansible.builtin.set_fact:
    asterisk_download_url: "https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-{{ asterisk_version }}-current.tar.gz"
    asterisk_archive: "/usr/src/asterisk-{{ asterisk_version }}-current.tar.gz"

- name: Download Asterisk source tarball
  ansible.builtin.get_url:
    url: "{{ asterisk_download_url }}"
    dest: "{{ asterisk_archive }}"
    mode: "0644"
  register: download_result
  until: download_result is succeeded
  retries: 3
  delay: 5

- name: Unpack Asterisk source tarball
  ansible.builtin.unarchive:
    src: "{{ asterisk_archive }}"
    dest: /usr/src
    remote_src: yes
  register: unarchive_result
  when: download_result is succeeded

- name: Find the extracted Asterisk source directory
  ansible.builtin.find:
    paths: /usr/src

    patterns: "asterisk-{{ asterisk_version }}.*"
    file_type: directory
  register: find_asterisk_dir
  when: unarchive_result is changed

- name: Fail if exactly one Asterisk source directory is not found
  ansible.builtin.fail:
    msg: "Could not find exactly one Asterisk source directory matching '/usr/src/asterisk-{{ asterisk_version }}.*'. Found: {{ find_asterisk_dir.files | map(attribute='path') | list }}"
  when: find_asterisk_dir.matched != 1

- name: Set fact for the actual Asterisk source directory path
  ansible.builtin.set_fact:
    actual_asterisk_src_dir: "{{ find_asterisk_dir.files[0].path }}"
  when: find_asterisk_dir.matched == 1

- name: Run Asterisk configure script
  ansible.builtin.command:
    cmd: ./configure --with-jansson-bundled --with-pjproject-bundled
    chdir: "{{ actual_asterisk_src_dir }}"
    creates: "{{ actual_asterisk_src_dir }}/Makefile"
  when: actual_asterisk_src_dir is defined

- name: Generate initial menuselect options file (make menuselect.makeopts)
  ansible.builtin.command:
    cmd: make menuselect.makeopts
    chdir: "{{ actual_asterisk_src_dir }}"

    creates: "{{ actual_asterisk_src_dir }}/menuselect.makeopts"
  when: actual_asterisk_src_dir is defined
  changed_when: false

- name: Apply menuselect options using the script
  ansible.builtin.command:
    cmd: >
      menuselect/menuselect
      --enable CORE-SOUNDS-EN-ULAW
      --enable MOH-OPSOUND-ULAW
      --enable EXTRA-SOUNDS-EN-ULAW
      --enable app_macro
      --enable format_mp3
      --enable res_config_odbc
      --enable res_odbc
      --enable cdr_adaptive_odbc
      --enable cel_odbc
      --enable res_calendar_caldav
      --enable res_calendar_ews
      --enable res_calendar_icalendar
      --enable res_crypto
      --enable res_http_websocket
      --enable res_pjsip_pubsub
      --enable res_pjsip_transport_websocket
      --enable res_srtp
      --enable codec_opus
      --disable BUILD_NATIVE
      --force
    chdir: "{{ actual_asterisk_src_dir }}"
  when: actual_asterisk_src_dir is defined

  register: menuselect_script_run
  changed_when: menuselect_script_run.rc == 0

- name: Compile Asterisk (make)
  ansible.builtin.command:
    cmd: make -j {{ ansible_processor_vcpus | default(2) }}
    chdir: "{{ actual_asterisk_src_dir }}"
    creates: "{{ actual_asterisk_src_dir }}/main/asterisk"
  when: actual_asterisk_src_dir is defined

- name: Install Asterisk (make install)
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ actual_asterisk_src_dir }}"
    creates: /usr/sbin/asterisk
  when: actual_asterisk_src_dir is defined

- name: Install Asterisk sample configuration files (optional but recommended)
  ansible.builtin.command:
    cmd: make samples
    chdir: "{{ actual_asterisk_src_dir }}"
    creates: /etc/asterisk/asterisk.conf.sample
  when: actual_asterisk_src_dir is defined

- name: Install Asterisk init scripts/systemd unit (make config)
  ansible.builtin.command:
    cmd: make config
    chdir: "{{ actual_asterisk_src_dir }}"
    creates: /lib/systemd/system/asterisk.service
  when: actual_asterisk_src_dir is defined

- name: Set ownership for Asterisk directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: asterisk
    group: asterisk
    recurse: yes
  with_items:
    - /etc/asterisk
    - /var/lib/asterisk
    - /var/log/asterisk
    - /var/spool/asterisk

- name: Ensure /var/run/asterisk exists
  ansible.builtin.file:
    path: /var/run/asterisk
    state: directory
    owner: asterisk
    group: asterisk
    mode: "0755"

- name: Configure ODBC INI file
  ansible.builtin.template:
    src: odbc.ini.j2
    dest: /etc/odbc.ini
    owner: root
    group: root
    mode: "0644"
  notify: Reload asterisk

- name: Configure ODBCINST INI file
  ansible.builtin.template:
    src: odbcinst.ini.j2
    dest: /etc/odbcinst.ini
    owner: root
    group: root
    mode: "0644"

- name: Enable and start Asterisk service
  ansible.builtin.systemd:
    name: asterisk
    enabled: yes
    state: started
    daemon_reload: yes
