---
-
  name: "Add NodeJS Repo"
  shell: curl -sL https://deb.nodesource.com/setup_{{nodejs_ver}}.x | sudo -E bash - > /tmp/node.log
  args:
    creates: /tmp/node.log
- name: Add PHP repo
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present
-
  name: "Updating System"
  apt:
    upgrade: full
    update_cache: yes
-
  name: Installing Packages
  apt:
    name: "{{packages}}"
    state: present
-
  name: Set swappiness
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swappiness=10
    backup: yes
    state: present
- 
  name: Set php8.2 version for cli
  shell: "{{item}}"
  with_items:
    - update-alternatives --set php /usr/bin/php8.2 
    - update-alternatives --set phar /usr/bin/phar8.2 
    - update-alternatives --set phar.phar /usr/bin/phar.phar8.2
-
  name: Reboot host
  reboot:
