---
- name: Add Webmin repository key
  ansible.builtin.apt_key:
    url: https://download.webmin.com/jcameron-key.asc
    state: present

- name: Add Webmin repository
  ansible.builtin.apt_repository:
    repo: deb https://download.webmin.com/download/repository stable contrib
    state: present
    filename: webmin
    update_cache: yes

- name: Install webmin package
  ansible.builtin.apt:
    name: webmin
    state: present
    update_cache: no
