---
- 
  name: Add Apt Key
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present
-
  name: Add Webmin Repo
  apt_repository:
    repo: deb http://download.webmin.com/download/repository sarge contrib
    state: present
-
  name: Install webmin
  apt:
    name: webmin
    update_cache: yes
    state: present
